import time
def dataAnalysis(df: "pandas.DataFrame"): # per non importare pandas gli dò il tipo così (funzionerebbe anche senza, però mi dà fastidio)
    print("sto analizzando il tuo ano...")
    print("analisi al 0%")
    time.sleep(0.5)
    print("analisi al 20%")
    time.sleep(0.5)
    print("analisi al 50%")
    time.sleep(0.5)
    print("analisi al 69%")
    time.sleep(0.5)
    print("analisi al 95%")
    time.sleep(0.5)
    print("analisi completata!")
    print("risultato: sei Super gay!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
